global:
  scrape_interval: 15s # Default is every 1 minute.

rule_files:
  - '/etc/prometheus/alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.1.26:9093']

scrape_configs:
  - job_name: 'collector'
    static_configs:
      - targets: ['otel-collector:8889']
